# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firebird/butler/fbdp.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66irebird/butler/fbdp.proto\x12\x0f\x66irebird.butler\x1a\x1cgoogle/protobuf/struct.proto\"}\n\x11\x46\x42\x44POpenDataframe\x12\x11\n\tdata_pipe\x18\x01 \x01(\t\x12\x13\n\x0bpipe_socket\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x61ta_format\x18\x03 \x01(\t\x12+\n\nparameters\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Structb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firebird.butler.fbdp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FBDPOPENDATAFRAME']._serialized_start=77
  _globals['_FBDPOPENDATAFRAME']._serialized_end=202
# @@protoc_insertion_point(module_scope)
