# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firebird/butler/fbsp.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from firebird.butler import fbsd_pb2 as firebird_dot_butler_dot_fbsd__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66irebird/butler/fbsp.proto\x12\x0f\x66irebird.butler\x1a\x19google/protobuf/any.proto\x1a\x1a\x66irebird/butler/fbsd.proto\"\xab\x01\n\x12\x46\x42SPHelloDataframe\x12\x35\n\x08instance\x18\x01 \x01(\x0b\x32#.firebird.butler.PeerIdentification\x12\x34\n\x06\x63lient\x18\x02 \x01(\x0b\x32$.firebird.butler.AgentIdentification\x12(\n\nsupplement\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"\xdb\x01\n\x14\x46\x42SPWelcomeDataframe\x12\x35\n\x08instance\x18\x01 \x01(\x0b\x32#.firebird.butler.PeerIdentification\x12\x35\n\x07service\x18\x02 \x01(\x0b\x32$.firebird.butler.AgentIdentification\x12+\n\x03\x61pi\x18\x03 \x03(\x0b\x32\x1e.firebird.butler.InterfaceSpec\x12(\n\nsupplement\x18\x04 \x03(\x0b\x32\x14.google.protobuf.Any\"M\n\x12\x46\x42SPCancelRequests\x12\r\n\x05token\x18\x01 \x01(\x0c\x12(\n\nsupplement\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"k\n\x14\x46\x42SPStateInformation\x12)\n\x05state\x18\x01 \x01(\x0e\x32\x1a.firebird.butler.StateEnum\x12(\n\nsupplement\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firebird.butler.fbsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FBSPHELLODATAFRAME']._serialized_start=103
  _globals['_FBSPHELLODATAFRAME']._serialized_end=274
  _globals['_FBSPWELCOMEDATAFRAME']._serialized_start=277
  _globals['_FBSPWELCOMEDATAFRAME']._serialized_end=496
  _globals['_FBSPCANCELREQUESTS']._serialized_start=498
  _globals['_FBSPCANCELREQUESTS']._serialized_end=575
  _globals['_FBSPSTATEINFORMATION']._serialized_start=577
  _globals['_FBSPSTATEINFORMATION']._serialized_end=684
# @@protoc_insertion_point(module_scope)
