# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firebird/butler/fbsp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from firebird.butler import fbsd_pb2 as firebird_dot_butler_dot_fbsd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='firebird/butler/fbsp.proto',
  package='firebird.butler',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x66irebird/butler/fbsp.proto\x12\x0f\x66irebird.butler\x1a\x19google/protobuf/any.proto\x1a\x1a\x66irebird/butler/fbsd.proto\"\xa7\x01\n\x0eHelloDataframe\x12\x35\n\x08instance\x18\x01 \x01(\x0b\x32#.firebird.butler.PeerIdentification\x12\x34\n\x06\x63lient\x18\x02 \x01(\x0b\x32$.firebird.butler.AgentIdentification\x12(\n\nsupplement\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"\xd7\x01\n\x10WelcomeDataframe\x12\x35\n\x08instance\x18\x01 \x01(\x0b\x32#.firebird.butler.PeerIdentification\x12\x35\n\x07service\x18\x02 \x01(\x0b\x32$.firebird.butler.AgentIdentification\x12+\n\x03\x61pi\x18\x03 \x03(\x0b\x32\x1e.firebird.butler.InterfaceSpec\x12(\n\nsupplement\x18\x04 \x03(\x0b\x32\x14.google.protobuf.Any\"I\n\x0e\x43\x61ncelRequests\x12\r\n\x05token\x18\x01 \x01(\x0c\x12(\n\nsupplement\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"c\n\x10StateInformation\x12%\n\x05state\x18\x01 \x01(\x0e\x32\x16.firebird.butler.State\x12(\n\nsupplement\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,firebird_dot_butler_dot_fbsd__pb2.DESCRIPTOR,])




_HELLODATAFRAME = _descriptor.Descriptor(
  name='HelloDataframe',
  full_name='firebird.butler.HelloDataframe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='firebird.butler.HelloDataframe.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='firebird.butler.HelloDataframe.client', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.butler.HelloDataframe.supplement', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=270,
)


_WELCOMEDATAFRAME = _descriptor.Descriptor(
  name='WelcomeDataframe',
  full_name='firebird.butler.WelcomeDataframe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='firebird.butler.WelcomeDataframe.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='firebird.butler.WelcomeDataframe.service', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api', full_name='firebird.butler.WelcomeDataframe.api', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.butler.WelcomeDataframe.supplement', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=488,
)


_CANCELREQUESTS = _descriptor.Descriptor(
  name='CancelRequests',
  full_name='firebird.butler.CancelRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='firebird.butler.CancelRequests.token', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.butler.CancelRequests.supplement', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=563,
)


_STATEINFORMATION = _descriptor.Descriptor(
  name='StateInformation',
  full_name='firebird.butler.StateInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='firebird.butler.StateInformation.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.butler.StateInformation.supplement', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=664,
)

_HELLODATAFRAME.fields_by_name['instance'].message_type = firebird_dot_butler_dot_fbsd__pb2._PEERIDENTIFICATION
_HELLODATAFRAME.fields_by_name['client'].message_type = firebird_dot_butler_dot_fbsd__pb2._AGENTIDENTIFICATION
_HELLODATAFRAME.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_WELCOMEDATAFRAME.fields_by_name['instance'].message_type = firebird_dot_butler_dot_fbsd__pb2._PEERIDENTIFICATION
_WELCOMEDATAFRAME.fields_by_name['service'].message_type = firebird_dot_butler_dot_fbsd__pb2._AGENTIDENTIFICATION
_WELCOMEDATAFRAME.fields_by_name['api'].message_type = firebird_dot_butler_dot_fbsd__pb2._INTERFACESPEC
_WELCOMEDATAFRAME.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_CANCELREQUESTS.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_STATEINFORMATION.fields_by_name['state'].enum_type = firebird_dot_butler_dot_fbsd__pb2._STATE
_STATEINFORMATION.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['HelloDataframe'] = _HELLODATAFRAME
DESCRIPTOR.message_types_by_name['WelcomeDataframe'] = _WELCOMEDATAFRAME
DESCRIPTOR.message_types_by_name['CancelRequests'] = _CANCELREQUESTS
DESCRIPTOR.message_types_by_name['StateInformation'] = _STATEINFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloDataframe = _reflection.GeneratedProtocolMessageType('HelloDataframe', (_message.Message,), dict(
  DESCRIPTOR = _HELLODATAFRAME,
  __module__ = 'firebird.butler.fbsp_pb2'
  # @@protoc_insertion_point(class_scope:firebird.butler.HelloDataframe)
  ))
_sym_db.RegisterMessage(HelloDataframe)

WelcomeDataframe = _reflection.GeneratedProtocolMessageType('WelcomeDataframe', (_message.Message,), dict(
  DESCRIPTOR = _WELCOMEDATAFRAME,
  __module__ = 'firebird.butler.fbsp_pb2'
  # @@protoc_insertion_point(class_scope:firebird.butler.WelcomeDataframe)
  ))
_sym_db.RegisterMessage(WelcomeDataframe)

CancelRequests = _reflection.GeneratedProtocolMessageType('CancelRequests', (_message.Message,), dict(
  DESCRIPTOR = _CANCELREQUESTS,
  __module__ = 'firebird.butler.fbsp_pb2'
  # @@protoc_insertion_point(class_scope:firebird.butler.CancelRequests)
  ))
_sym_db.RegisterMessage(CancelRequests)

StateInformation = _reflection.GeneratedProtocolMessageType('StateInformation', (_message.Message,), dict(
  DESCRIPTOR = _STATEINFORMATION,
  __module__ = 'firebird.butler.fbsp_pb2'
  # @@protoc_insertion_point(class_scope:firebird.butler.StateInformation)
  ))
_sym_db.RegisterMessage(StateInformation)


# @@protoc_insertion_point(module_scope)
