# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firebird/butler/fbsp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from firebird.butler import fbsd_pb2 as firebird_dot_butler_dot_fbsd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='firebird/butler/fbsp.proto',
  package='firebird.butler',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x66irebird/butler/fbsp.proto\x12\x0f\x66irebird.butler\x1a\x19google/protobuf/any.proto\x1a\x1a\x66irebird/butler/fbsd.proto\"\xab\x01\n\x12\x46\x42SPHelloDataframe\x12\x35\n\x08instance\x18\x01 \x01(\x0b\x32#.firebird.butler.PeerIdentification\x12\x34\n\x06\x63lient\x18\x02 \x01(\x0b\x32$.firebird.butler.AgentIdentification\x12(\n\nsupplement\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"\xdb\x01\n\x14\x46\x42SPWelcomeDataframe\x12\x35\n\x08instance\x18\x01 \x01(\x0b\x32#.firebird.butler.PeerIdentification\x12\x35\n\x07service\x18\x02 \x01(\x0b\x32$.firebird.butler.AgentIdentification\x12+\n\x03\x61pi\x18\x03 \x03(\x0b\x32\x1e.firebird.butler.InterfaceSpec\x12(\n\nsupplement\x18\x04 \x03(\x0b\x32\x14.google.protobuf.Any\"M\n\x12\x46\x42SPCancelRequests\x12\r\n\x05token\x18\x01 \x01(\x0c\x12(\n\nsupplement\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"k\n\x14\x46\x42SPStateInformation\x12)\n\x05state\x18\x01 \x01(\x0e\x32\x1a.firebird.butler.StateEnum\x12(\n\nsupplement\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,firebird_dot_butler_dot_fbsd__pb2.DESCRIPTOR,])




_FBSPHELLODATAFRAME = _descriptor.Descriptor(
  name='FBSPHelloDataframe',
  full_name='firebird.butler.FBSPHelloDataframe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='firebird.butler.FBSPHelloDataframe.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='firebird.butler.FBSPHelloDataframe.client', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.butler.FBSPHelloDataframe.supplement', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=274,
)


_FBSPWELCOMEDATAFRAME = _descriptor.Descriptor(
  name='FBSPWelcomeDataframe',
  full_name='firebird.butler.FBSPWelcomeDataframe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='firebird.butler.FBSPWelcomeDataframe.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='firebird.butler.FBSPWelcomeDataframe.service', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api', full_name='firebird.butler.FBSPWelcomeDataframe.api', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.butler.FBSPWelcomeDataframe.supplement', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=496,
)


_FBSPCANCELREQUESTS = _descriptor.Descriptor(
  name='FBSPCancelRequests',
  full_name='firebird.butler.FBSPCancelRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='firebird.butler.FBSPCancelRequests.token', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.butler.FBSPCancelRequests.supplement', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=575,
)


_FBSPSTATEINFORMATION = _descriptor.Descriptor(
  name='FBSPStateInformation',
  full_name='firebird.butler.FBSPStateInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='firebird.butler.FBSPStateInformation.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.butler.FBSPStateInformation.supplement', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=684,
)

_FBSPHELLODATAFRAME.fields_by_name['instance'].message_type = firebird_dot_butler_dot_fbsd__pb2._PEERIDENTIFICATION
_FBSPHELLODATAFRAME.fields_by_name['client'].message_type = firebird_dot_butler_dot_fbsd__pb2._AGENTIDENTIFICATION
_FBSPHELLODATAFRAME.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_FBSPWELCOMEDATAFRAME.fields_by_name['instance'].message_type = firebird_dot_butler_dot_fbsd__pb2._PEERIDENTIFICATION
_FBSPWELCOMEDATAFRAME.fields_by_name['service'].message_type = firebird_dot_butler_dot_fbsd__pb2._AGENTIDENTIFICATION
_FBSPWELCOMEDATAFRAME.fields_by_name['api'].message_type = firebird_dot_butler_dot_fbsd__pb2._INTERFACESPEC
_FBSPWELCOMEDATAFRAME.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_FBSPCANCELREQUESTS.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_FBSPSTATEINFORMATION.fields_by_name['state'].enum_type = firebird_dot_butler_dot_fbsd__pb2._STATEENUM
_FBSPSTATEINFORMATION.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['FBSPHelloDataframe'] = _FBSPHELLODATAFRAME
DESCRIPTOR.message_types_by_name['FBSPWelcomeDataframe'] = _FBSPWELCOMEDATAFRAME
DESCRIPTOR.message_types_by_name['FBSPCancelRequests'] = _FBSPCANCELREQUESTS
DESCRIPTOR.message_types_by_name['FBSPStateInformation'] = _FBSPSTATEINFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FBSPHelloDataframe = _reflection.GeneratedProtocolMessageType('FBSPHelloDataframe', (_message.Message,), {
  'DESCRIPTOR' : _FBSPHELLODATAFRAME,
  '__module__' : 'firebird.butler.fbsp_pb2'
  # @@protoc_insertion_point(class_scope:firebird.butler.FBSPHelloDataframe)
  })
_sym_db.RegisterMessage(FBSPHelloDataframe)

FBSPWelcomeDataframe = _reflection.GeneratedProtocolMessageType('FBSPWelcomeDataframe', (_message.Message,), {
  'DESCRIPTOR' : _FBSPWELCOMEDATAFRAME,
  '__module__' : 'firebird.butler.fbsp_pb2'
  # @@protoc_insertion_point(class_scope:firebird.butler.FBSPWelcomeDataframe)
  })
_sym_db.RegisterMessage(FBSPWelcomeDataframe)

FBSPCancelRequests = _reflection.GeneratedProtocolMessageType('FBSPCancelRequests', (_message.Message,), {
  'DESCRIPTOR' : _FBSPCANCELREQUESTS,
  '__module__' : 'firebird.butler.fbsp_pb2'
  # @@protoc_insertion_point(class_scope:firebird.butler.FBSPCancelRequests)
  })
_sym_db.RegisterMessage(FBSPCancelRequests)

FBSPStateInformation = _reflection.GeneratedProtocolMessageType('FBSPStateInformation', (_message.Message,), {
  'DESCRIPTOR' : _FBSPSTATEINFORMATION,
  '__module__' : 'firebird.butler.fbsp_pb2'
  # @@protoc_insertion_point(class_scope:firebird.butler.FBSPStateInformation)
  })
_sym_db.RegisterMessage(FBSPStateInformation)


# @@protoc_insertion_point(module_scope)
